import "./globals.css";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import Navbar from "./components/navbar/Navbar";
import Modal from "./components/modals/Modal";
import RegisterModal from "./components/modals/RegisterModal";
import ToasterProvider from "./providers/ToasterProvider";
import LoginModal from "./components/modals/LoginModal";
import getCurrentUser from "./actions/getCurrentUser";
import RentModal from "./components/modals/RentModal";
import SearchModal from "./components/modals/SearchModal";
import Skeleton, { SkeletonTheme } from "react-loading-skeleton";
import AuthContext from "./context/AuthContext";
import ActiveStatus from "./components/ActiveStatus";
import { CrispProvider } from "./components/crisp-provider";
import ConfettiProvider from "./providers/ConfettiProvider";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gobnb 3",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <CrispProvider />
          <ConfettiProvider/>
          <ToasterProvider />
          <SearchModal />
          <RentModal />
          <LoginModal />
          <RegisterModal />
          <ActiveStatus />
          <Navbar currentUser={currentUser!} />
          <div className="pt-24 h-full">{children}</div>
        </AuthContext>
      </body>
    </html>
  );
}

export const dynamic = "force-dynamic";
